name: orb_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

workspace:
  - local_packages/orb_ui_kit

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  helm: ^0.0.1
  http: ^1.2.2
  intl: ^0.20.2
  meta: ^1.16.0
  orb_ui_kit: ^0.0.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
